### ISSUE TITLE
Wrong IP show if my site behind a reverse proxy

### ISSUE THREAD

**Issue by webspilka** [bonny/WordPress-Simple-History#106]
Hi 
I install Simple History.  Log shows something like:
`` Anonymous user from 108.61.171.45
108.61.171.45, **but it's my server IP.**
In other plugin I find option handles site/server behind reverse proxy. After the activation of other plug-ins are beginning to show the correct address. For example: https://ru.wordpress.org/plugins/wp-cerber/

May you also have this option?
![proxy](https://cloud.githubusercontent.com/assets/1138069/12778305/c0bd669a-ca6a-11e5-8aa9-06eb084e0552.png)

**Comment by webspilka** [comment]
look pls at code
http://roshanbh.com.np/2007/12/getting-real-ip-address-in-php.html
or 
http://stackoverflow.com/questions/3003145/how-to-get-the-client-ip-address-in-php/3003233#3003233

**Comment by bonny** [comment]
Thanks for the report. The plugin does store any of these if they exist in header:

			'HTTP_CLIENT_IP',
			'HTTP_X_FORWARDED_FOR',
			'HTTP_X_FORWARDED',
			'HTTP_X_CLUSTER_CLIENT_IP',
			'HTTP_FORWARDED_FOR',
			'HTTP_FORWARDED'

Because these headers can be set by anyone I have chosen not to show them by default. You can however display them if you click on the date and time of the event. Then in the table with info you should see any of the headers above, if they was in the header of the request.
