### ISSUE TITLE
Should give options on what to log

### ISSUE THREAD

**Issue by iandouglas** [bonny/WordPress-Simple-History#107]
Hey there,

While I always appreciate WP plugins that offer support and are open to feedback, I had to disable your plugin today because it was logging _everything_ including failed logins. 8M failed logins later, we have a 30GB InnoDB file that we can't shrink.

It would be nice if, on the settings for your plugin, you gave the user the ability checkbox which things they want logged to avoid this for others in the future.

**Comment by bonny** [comment]
Thanks for the feedback. These brute force attacks are indeed a problem and I'm looking into a solution to keep the log from growing to big.

**Comment by bonny** [comment]
Btw, if you have that many failed login attempts you may wanna install something like Jetpack and activate its protect feature!

**Comment by pothi** [comment]
Hi @bonny ,

I had a similar issue, but less frustrating than the OP. Had over 70k failed login attempts consuming over 50mb memory.

Rather than giving us the option on what to log (as requested by OP), I'd appreciate if the plugin stops logging after certain threshold of repeated activity (for example after 1k failed login attempts in an hour).

Now, I use a different mechanism to prevent too many login attempts in my personal site. It's a combination of [rate limit at the server level](http://nginx.org/r/limit_req) and a [plugin to change the login URL](https://wordpress.org/plugins/sf-move-login/). Unfortunately, I don't have privilege to get access to the server everywhere. Nor, I can change the login URL. 🤣  So, I'd appreciate if there is a way to stop the logging and then possibly email the site admin about the logging being stopped. 🤣  Am I asking too much?

Please consider it as a feature request from me. It is not a bug. It does what it is meant to.

Best,
A very happy user of your plugin.

**Comment by webeks** [comment]
I would also need this. I dont care for much logs, however I need a way to know **from which IP certain content** originated since we have public contributions allowed. 

Besides I would also recommend the ability to clear log history by type.

**Comment by bonny** [comment]
This is possible now with an add-on:
https://simple-history.com/add-ons/extended-settings/#limit-number-of-failed-login-attempts
