### ISSUE TITLE
Option to manually add a log entry

### ISSUE THREAD

**Issue by Photosynthesis** [bonny/WordPress-Simple-History#110]
It would be wonderful to have a way for an admin to manually add a log entry for an action that is not captured by Simple History. (In this particular case: deployment from staging to production on a WP Engine account).

This could be accomplished with a fairly small addition to the admin page, and could also be optional through a setting in the plugin settings page.

See screenshots for a couple of UI options.

Let me know if you think this feature would be of interest as a PR that could be included in future plugin updates.

Thanks for the excellent plugin. 

![settings](https://cloud.githubusercontent.com/assets/4992900/14297665/f1e24cf4-fb34-11e5-9935-0acdf9a97cb8.jpg)
![admin-page](https://cloud.githubusercontent.com/assets/4992900/14297666/f4b4b07a-fb34-11e5-9a05-9b39abc4261f.jpg)

**Comment by bonny** [comment]
I like the idea! If you want to do this as a PR that would be great. Your UI looks good, simple and discrete, I like that. 

I think that the manual entries should be an own "logger" so events easily could be filtered and found and so on. Also all code should be put into a drop in, so it is its fully own component.

Let me know if you will do this,, otherwise I might do it because it's a great idea :)

**Comment by bonny** [comment]
Also requested in the support forums:
https://wordpress.org/support/topic/feature-request-allow-for-manual-history-log-too/#post-13091790

**Comment by bonny** [comment]
Closing in favor of #446.
