### ISSUE TITLE
Move simple_history_page from Dashboard (or add filter for optionally doing so)

### ISSUE THREAD

**Issue by fiskhandlarn** [bonny/WordPress-Simple-History#140]
Let me start with saying I really like this plugin. :)

I often hide the wp-admin Dashboard for clients/editors with https://github.com/wordplate/plate, thus making this plugin impossible to find. 

What is the reasoning behind putting this plugin under the Dashboard? I don't think I've ever seen that behaviour in a plugin. Usually plugins make their own root page or add themselves under Tools. Would it be possible to change the location to it's own root page or under Tools? Or at least create a filter for this?

**Comment by bonny** [comment]
I did put it below the dashboard to keep it out of the way and make it discrete. I don't like plugins that add themself to the main menu. Few plugins are that important to the end user. The activity feed of simple history felt like a dashboard-ish page so that's why I put it there.

To be able to put it on it's own menu on the top level using a setting or filter is perhaps a good idea. I'll add it to my todo list.

**Comment by bonny** [comment]
Sure, if you want to make a PR that would be awesome!

**Comment by JoshuaLewis** [comment]
Checking in on this. Would be great to have simple history on the frontend. My reasons are that I want contributions to be the soul of the site for site activity. A friend of mine highlighted to me that social media is cluttered with distractions. Simple history focuses on what's most important which is exactly what we need. If shown on the frontend I could display amazing places people have gone to (reviews) along with events/content that people are genuinely interested in. This would inspire people to read info and go to awesome places instead of trying to create another distraction. Also it would make it easier for folks to keep track of media/posts that were attached to their pages so that content would be well managed.

If the shortcode had various filters such as [simplehistory member="34" activity="posts" category="events"] we could replace 34 with a list of users that person is following so that friends can keep track of their friend's activity. I could then store profile preferences to load out default history items the user wants to see each time they take a look.

This would open up the door to allowing us to write our own public dashboard to make history organized in sub-tabs. Then create my own admin dashboard with tabs such as "Deleted users", "Recent 404s", "Failed user logins" and logins from known bad IP addresses.

**Comment by fiskhandlarn** [comment]
> Sure, if you want to make a PR that would be awesome!

https://github.com/bonny/WordPress-Simple-History/pull/168

**Comment by bonny** [comment]
> > Sure, if you want to make a PR that would be awesome!
> 
> #168

Does this always add in under tools or is it possible to modify using a filter or similar? I'm ok with the option to have it under tools using a filter but not to be automagically moved there when people update the plugin.

**Comment by fiskhandlarn** [comment]
@bonny It's kind of tied in with CSS (which will probably get pretty bloated if it should support all locations in wp-admin), but I can make a new PR if you like.

**Comment by bonny** [comment]
Ah yes, but maybe it doesn't have to support all locations, just below dashboard as default and under tools when using a filter like "simple-history/page/location" and returning the value "tools". If you can modify your PR to include that that would be awesome. Really appreciate your effort!

**Comment by fiskhandlarn** [comment]
@bonny Updated my PR: https://github.com/bonny/WordPress-Simple-History/pull/168. I've removed `.dashboard_page_simple_history_page` from the CSS to make it work in any location, I hope this was alright.

**Comment by fiskhandlarn** [comment]
@bonny bump :)

**Comment by bonny** [comment]
yes sorry, gonna take a look soon!

**Comment by bonny** [comment]
Tested now and works fine – felt strange to have the log page below the tools menu however :) Will be included in the next release anyway so thanks a lot for the help!
