### ISSUE TITLE
Update and put select2 into own namespace

### ISSUE THREAD

**Issue by ajoah** [bonny/WordPress-Simple-History#223]
Hi,

Is it possible to update select2 ?

With select2 4.0.5, there is an issue with french translation (and maybe other languages) : 

![image](https://user-images.githubusercontent.com/10757301/92378036-6469b080-f105-11ea-92d7-a7dcb12e9f02.png)

It displays "s" instead of "Saisissez au moins 2 caractères"

**Comment by bonny** [comment]
Yes, I'll try to take a look at that.

**Comment by bonny** [comment]
There are more problems related to Select2 when multiple plugins use different versions. For example this bug is because another plugin is using another version of Select2:
https://wordpress.org/support/topic/bug-search-is-not-working/

WP ShortCake seems to have a possible solution:
https://github.com/wp-shortcake/shortcake/pull/702

**Comment by bonny** [comment]
Possibly related:
https://wordpress.org/support/topic/search-box-hidden/
