### ISSUE TITLE
Log when admin sends reset password link

### ISSUE THREAD

**Issue by bonny** [bonny/WordPress-Simple-History#256]
https://make.wordpress.org/core/2021/02/22/send-reset-password-links-in-wordpress-5-7/

**Comment by sokai** [comment]
FYI: I can see this messages in the current version.

Here is a example message.

Conditions: Me (= Admin) sent a password reset link to an existing user (`user`).
Message:
* Line 1: `Anonymous web user 12:07 (9 minutes ago)`
* Line 2: `Requested a password reset link for user with login 'user' and email 'user@my-doma.in' notice`

For me/my installation the requested message is logged.
Currently the only _problem_ is, that in line 1 `Anonymous web user` instead of the correct user (= me = `You`) is shown.

**Comment by bonny** [comment]
Thanks for the report, I recently saw that bug myself so it will be fixed in the next version.
