### ISSUE TITLE
Fine Tune what is logged

### ISSUE THREAD

**Issue by getdave** [bonny/WordPress-Simple-History#45]
Hi. Firstly great Plugin. Thanks!

Unfortunately my website DB is getting overloaded by the entires created by this Plugin. What I really need is a way to fine tune what is/isn't logged.

Is this possible/in the works?

Much appreciated

**Comment by bonny** [comment]
Hi + thanks!

Can you clearify what you mean by "overloaded"?

**Comment by bonny** [comment]
Since version 2.0.22 you can now control this pretty much in anyway you may want it.

There are 2 filters of interest:

`simple_history/logger/load_logger` and `simple_history/simple_logger/log_message_key`. 

Take a look at [the examples file](https://github.com/bonny/WordPress-Simple-History/blob/master/examples/examples.php) for some examples.
